[package]
name = "hijacker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
log = { version = "0.4.27", features = ["release_max_level_warn"] }
pipewire = "0.8.0"
rodio = "0.20.1"
tracing-subscriber = "0.3.19"
